export { Layout} from './Layout';
export { Home } from './Home';
export { Analisis } from './Analisis';
export { ServiceTransformation } from './ServiceTransformation';
export { Automatization } from './Automatization';
export { Colaboracion } from './Colaboracion';
export { Gestion } from './Gestion';
export { Guias } from './Guias';
export { Webinars } from './Webinars';
export { Estudiocasos } from './Estudiocasos';
export { Ebooks } from './Ebooks';
export { ScrollToTopOnNavigate } from './ScrollToTopOnNavigate';
export { AnimatedRoute } from './AnimatedRoute';
export { Footer } from './Footer';